pipeline {
    agent any

    environment {
        KUBECONFIG = "/var/lib/jenkins/.kube/config"
    }

    stages {
        stage('Apply Kubernetes Manifests') {
            steps {
                echo 'Deploying application to Kubernetes'
                sh """
                    export KUBECONFIG="/var/lib/jenkins/.kube/config"
                    cd manifest
                    kubectl apply -f .
                """
            }
        }
    }

    post {
        success {
            echo 'Pipeline successfully completed.'
        }

        failure {
            echo 'Pipeline failed.'
        }
    }
}